# Site settings
title: 1000genomes
email: info@1000genomes.org
description: > # this means to ignore newlines until "baseurl:"
  1000 genomes is an international research effort to establish by far the most detailed catalogue of human genetic variation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hipsci.github.io" # the base hostname & protocol for your site
permalink: /:categories/:title
gems:
    - jekyll-redirect-from

# Build settings
markdown: kramdown
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
