# Site settings
title: 1000genomes
email: info@1000genomes.org
description: > # this means to ignore newlines until "baseurl:"
  1000 genomes is an international research effort to establish by far the most detailed catalogue of human genetic variation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.1000genomes.org" # the base hostname & protocol for your site
permalink: /:categories/:title/
gems:
    - jekyll-redirect-from
collections:
    faq_categories:
        output: true
        permalink: /category/:path/
    faq:
        output: true
        permalink: /faq/:path/

# Build settings
markdown: kramdown
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
default_sitemap_lastmod: 2015-12-11T00:00:00+00:00
